name: onstovebinder
channels:
  - conda-forge
dependencies:
  - dill
  - geopandas
  - libgdal==3.5.2
  - matplotlib
  - plotnine
  - psutil
  - psycopg2
  - pyproj==3.3.1
  - python>=3.10
  - python-decouple
  - rasterio
  - scikit-image
  - svgpathtools
  - svgpath2mpl
