name: OnStove tests
on:
  push:
    branches: ['tests_technology']
    paths: ['onstove/*', 'onstove/tests/*']

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: ["ubuntu-latest"]
            python-version: ["3.10.*"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: onstove-tests
          environment-file: environment-tests.yml
          auto-activate-base: false
      - name: Run pytest
        shell: bash -l {0}
        run: |
            pytest
