name: OnStove tests
on:
  push:
    branches: ['tests_technology']
    paths: ['onstove/*', 'onstove/tests/*']

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: ["ubuntu-latest"]
            python-version: ["3.10.*"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: onstove-tests
          environment-file: environment-tests.yml
          auto-activate-base: false
      # - name: Lint
        # shell: bash -l {0}
        # run: |
            # python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run pytest
        shell: bash -l {0}
        run: |
            pytest
